# Generated by Django 3.2.14 on 2022-07-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_siting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breeds',
            field=models.ManyToManyField(related_name='animals', to='animal_siting.Breed', verbose_name='list of breeds'),
        ),
        migrations.AlterField(
            model_name='sitinglist',
            name='created',
            field=models.DateField(),
        ),
    ]
